# Generated by Django 2.1.7 on 2019-12-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
    ]
