# Generated by Django 2.1.7 on 2019-12-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_auto_20191204_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddedamount',
            name='cost',
            field=models.FloatField(),
        ),
    ]
