# Generated by Django 2.1.7 on 2019-12-09 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0004_auto_20191204_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddedamount',
            name='pincode',
            field=models.PositiveIntegerField(default=533006),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='biddedamount',
            unique_together={('name', 'product', 'pincode')},
        ),
    ]
