# Generated by Django 2.1.7 on 2019-12-09 16:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0005_auto_20191209_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='biddedamount',
            unique_together={('product', 'name', 'pincode')},
        ),
    ]
