# Generated by Django 2.1.7 on 2019-12-10 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0006_auto_20191209_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='pending_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('pincode', models.PositiveIntegerField()),
                ('phone_num', models.PositiveIntegerField()),
                ('customer', models.CharField(max_length=150)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
