# Generated by Django 2.1.7 on 2019-12-12 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0007_pending_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddedamount',
            name='location',
            field=models.CharField(default='kakinada', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='biddedamount',
            unique_together={('product', 'name', 'location')},
        ),
    ]
