# Generated by Django 2.1.7 on 2019-12-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0010_auto_20191212_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_orders',
            name='order_id',
            field=models.CharField(default='asfrhsghahsa', max_length=100),
            preserve_default=False,
        ),
    ]
