# Generated by Django 2.1.7 on 2019-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0011_pending_orders_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_orders',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Shipped', 'Order Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order Received', max_length=100),
        ),
    ]
